const products = [
  {
    id: 1,
    name: "VBucks Pack",
    price: 9.99,
    description: "Get 1000 Fortnite VBucks instantly.",
    image: "https://via.placeholder.com/320x180/5500aa/fff?text=VBucks+Pack",
    stock: 10,
    deal: true,
    dealPrice: 7.99,
  },
  {
    id: 2,
    name: "Fortnite Account",
    price: 59.99,
    description: "Premium Fortnite account with skins and emotes.",
    image: "https://via.placeholder.com/320x180/5500aa/fff?text=Fortnite+Account",
    stock: 5,
  },
  {
    id: 3,
    name: "Valorant Points",
    price: 9.99,
    description: "Instant Valorant Points.",
    image: "https://via.placeholder.com/320x180/5500aa/fff?text=Valorant+Points",
    stock: 0,
  },
  {
    id: 4,
    name: "Discord Nitro",
    price: 19.99,
    description: "1 month Discord Nitro subscription.",
    image: "https://via.placeholder.com/320x180/5500aa/fff?text=Discord+Nitro",
    stock: 15,
  },
  {
    id: 5,
    name: "Server Boost",
    price: 4.99,
    description: "1 Server Boost for your favorite Discord server.",
    image: "https://via.placeholder.com/320x180/5500aa/fff?text=Server+Boost",
    stock: 20,
  },
];
